# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateusername', models.CharField(max_length=20)),
                ('operatedate', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('mealnames', models.CharField(max_length=512)),
                ('status', models.IntegerField()),
                ('remark', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderAppId', models.IntegerField()),
                ('operateusername', models.CharField(max_length=20)),
                ('operatedate', models.DateField()),
                ('mealname', models.CharField(max_length=30)),
                ('ordernum', models.IntegerField()),
                ('remark', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
