# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoApp', '0002_orderapplication_restname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapplication',
            name='remark',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='orderapplication',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='remark',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
