# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoApp', '0004_auto_20161024_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapplication',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
